### ISSUE TITLE
建议Special Judge采用Testlib

### ISSUE THREAD

**Issue by billchenchina** [SniffesTheRose/EchoJudge#8]
建议Special Judge采用[Testlib](https://github.com/MikeMirzayanov/testlib)。

[洛谷](https://www.luogu.org)，[UOJ](https://github.com/vfleaking/UOJ)，[SYZOJ](https://github.com/SYZOJ/SYZOJ)均采用了Testlib库，这样能让Special Judge功能更通用。

**Comment by MrMorning** [comment]
感谢建议.
下一版本的更新中将会在SPJ配置中加入testlib选项.

**Comment by MrMorning** [comment]
新版本的EchoJudge已经对Testlib提供了支持。
欢迎下载试用！
